name: fpl_prediction-py39
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - mlflow
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - tensorflow
    - tensorflow-lattice 
    - pydot
    - seaborn
    - ipykernel
    - jupyterlab
    - lightgbm
    - tqdm
    - optuna
    - pyaml
    - click